// <auto-generated />
namespace SiliconIndy.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addvalueforlessontype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addvalueforlessontype));
        
        string IMigrationMetadata.Id
        {
            get { return "201808170413569_addvalueforlessontype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
